"""add_user_follows_system

Revision ID: 0004
Revises: 0003
Create Date: 2024-05-30 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003' # Points to the 'add_comments_system' migration
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_follows',
        sa.Column('follower_id', sa.Integer(), nullable=False),
        sa.Column('followed_id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True, server_default=sa.func.current_timestamp()), # Added server_default
        sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name=op.f('fk_user_follows_followed_id_user')),
        sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name=op.f('fk_user_follows_follower_id_user')),
        sa.PrimaryKeyConstraint('follower_id', 'followed_id', name=op.f('pk_user_follows'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_follows')
    # ### end Alembic commands ###
