"""add_uuid_to_blocks

Revision ID: 0005
Revises: 0004
Create Date: 2024-05-30 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import uuid # For generating UUIDs during data migration

# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004' # Points to 'add_user_follows_system'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first to allow populating existing rows
    op.add_column('climbing_block', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_unique_constraint(op.f('uq_climbing_block_uuid'), 'climbing_block', ['uuid']) # Explicit unique constraint name
    op.create_index(op.f('ix_climbing_block_uuid'), 'climbing_block', ['uuid'], unique=False) # Index can be non-unique if unique constraint handles it, but usually true for UUID lookups

    # Data migration: Populate UUID for existing rows
    # Define table and columns for the data migration part
    climbing_block_table = sa.table('climbing_block',
        sa.column('id', sa.Integer),
        sa.column('uuid', sa.String(length=36))
    )

    conn = op.get_bind()
    # Select all rows (assuming all existing rows need a UUID)
    # It's safer to select rows where uuid IS NULL if this script could be re-run partially
    results = conn.execute(sa.select(climbing_block_table.c.id).where(climbing_block_table.c.uuid == None)).fetchall()

    for row in results:
        block_id = row[0]
        op.execute(
            climbing_block_table.update().where(climbing_block_table.c.id == block_id).values(uuid=str(uuid.uuid4()))
        )

    # After populating, make the column non-nullable
    op.alter_column('climbing_block', 'uuid', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_climbing_block_uuid'), table_name='climbing_block')
    op.drop_constraint(op.f('uq_climbing_block_uuid'), 'climbing_block', type_='unique') # Drop unique constraint by name
    op.drop_column('climbing_block', 'uuid')
    # ### end Alembic commands ###
