"""add_badges_system

Revision ID: 0006
Revises: 0005
Create Date: 2024-05-30 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Example, if you were using specific types

# revision identifiers, used by Alembic.
revision = '0006'
down_revision = '0005' # Points to 'add_uuid_to_blocks'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('icon_url', sa.String(length=255), nullable=True),
        sa.Column('criteria', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_badge')),
        sa.UniqueConstraint('name', name=op.f('uq_badge_name')) # Explicitly named unique constraint
    )
    op.create_table('user_badge',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('badge_id', sa.Integer(), nullable=False),
        sa.Column('earned_at', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()), # Added server_default
        sa.ForeignKeyConstraint(['badge_id'], ['badge.id'], name=op.f('fk_user_badge_badge_id_badge')),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_badge_user_id_user')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user_badge')),
        sa.UniqueConstraint('user_id', 'badge_id', name=op.f('uq_user_badge')) # Explicitly named unique constraint
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_badge')
    op.drop_table('badge')
    # ### end Alembic commands ###
