"""add_user_notification_prefs

Revision ID: 0008
Revises: 0007
Create Date: 2024-05-30 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0008'
down_revision = '0007' # Points to 'add_push_subscriptions'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_on_comment_on_own_block', sa.Boolean(), server_default=sa.true(), nullable=True))
        batch_op.add_column(sa.Column('notify_on_badge_earned', sa.Boolean(), server_default=sa.true(), nullable=True))
        batch_op.add_column(sa.Column('notify_on_new_block_by_followed', sa.Boolean(), server_default=sa.true(), nullable=True))

    # Ensure existing rows get the default value True (1 for SQLite boolean)
    # This is important because server_default only applies to new rows for some DBs/configs
    # or if the column was added as nullable without a default initially.
    op.execute("UPDATE \"user\" SET notify_on_comment_on_own_block = 1 WHERE notify_on_comment_on_own_block IS NULL")
    op.execute("UPDATE \"user\" SET notify_on_badge_earned = 1 WHERE notify_on_badge_earned IS NULL")
    op.execute("UPDATE \"user\" SET notify_on_new_block_by_followed = 1 WHERE notify_on_new_block_by_followed IS NULL")

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('notify_on_comment_on_own_block', nullable=False)
        batch_op.alter_column('notify_on_badge_earned', nullable=False)
        batch_op.alter_column('notify_on_new_block_by_followed', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notify_on_new_block_by_followed')
        batch_op.drop_column('notify_on_badge_earned')
        batch_op.drop_column('notify_on_comment_on_own_block')
    # ### end Alembic commands ###
