"""add_is_admin_to_user

Revision ID: 0009
Revises: 0008
Create Date: 2024-05-30 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0009'
down_revision = '0008' # Points to 'add_push_subscriptions'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True, server_default=sa.false()))

    # Backfill existing rows. For SQLite, booleans are often 0 or 1.
    # The specific SQL might vary slightly by DB if not using SQLAlchemy Core expressions.
    # Using a general op.execute for wider compatibility.
    op.execute('UPDATE "user" SET is_admin = 0 WHERE is_admin IS NULL') # Ensure existing users are not admins

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
    # ### end Alembic commands ###
