"""add_updated_at_to_climbing_block

Revision ID: 0010
Revises: 0009
Create Date: 2024-05-30 18:05:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0010'
down_revision = '0009' # Points to 'add_is_admin_to_user'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climbing_block', schema=None) as batch_op:
        # Add column as nullable first for backfill
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # Backfill existing rows: Set updated_at to created_at or current_timestamp
    # Using created_at is a common strategy for initial backfill.
    # If created_at is not available, current_timestamp can be used.
    # The model has default=datetime.utcnow, onupdate=datetime.utcnow, so new rows are handled.
    # This migration handles existing rows.
    op.execute('UPDATE climbing_block SET updated_at = created_at WHERE updated_at IS NULL')
    # As a fallback if created_at might not exist (though it should):
    # op.execute('UPDATE climbing_block SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL')


    with op.batch_alter_table('climbing_block', schema=None) as batch_op:
        # Now make it non-nullable
        batch_op.alter_column('updated_at', nullable=False, server_default=sa.func.current_timestamp()) # Add server_default for future DB-level inserts if any
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climbing_block', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
    # ### end Alembic commands ###
