"""add_created_at_to_user

Revision ID: 0011
Revises: 0010
Create Date: 2024-05-30 19:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0011'
down_revision = '0010' # Points to 'add_updated_at_to_climbing_block'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.current_timestamp()))

    # Backfill existing rows.
    # Using a general op.execute for wider compatibility if server_default doesn't backfill.
    # For SQLite, CURRENT_TIMESTAMP is fine. For others, now() or similar might be used.
    op.execute('UPDATE "user" SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
    # ### end Alembic commands ###
