"""add_is_active_to_user

Revision ID: 0012
Revises: 0011
Create Date: 2024-05-30 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0012'
down_revision = '0011' # Points to 'add_created_at_to_user'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True, server_default=sa.true()))

    # Backfill existing rows. For SQLite, True is 1.
    # This ensures that users created before this migration are active by default.
    op.execute('UPDATE "user" SET is_active = 1 WHERE is_active IS NULL')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')
    # ### end Alembic commands ###
