"""add status to climbing block

Revision ID: 0013
Revises: 0012
Create Date: YYYY-MM-DD HH:MM:SS.mmmmmm

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0013'
down_revision = '0012' # This should be the actual revision ID of the migration '0012_add_is_active_to_user.py'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climbing_block', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True, server_default='active'))

    # Update existing rows to set a default status
    # Ensure this SQL is appropriate for your DB (e.g., SQLite, PostgreSQL)
    op.execute("UPDATE climbing_block SET status = 'active' WHERE status IS NULL")

    with op.batch_alter_table('climbing_block', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climbing_block', schema=None) as batch_op:
        batch_op.drop_column('status')
    # ### end Alembic commands ###
