"""create block_proposal table

Revision ID: 0014
Revises: 0013
Create Date: YYYY-MM-DD HH:MM:SS.mmmmmm

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Example, if you need specific types not in sa

# revision identifiers, used by Alembic.
revision = '0014'
down_revision = '0013' # Previous migration was '0013_add_status_to_climbing_block.py'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposer_id', sa.Integer(), nullable=False),
    sa.Column('location_description', sa.Text(), nullable=False),
    sa.Column('climb_description', sa.Text(), nullable=True),
    sa.Column('proposed_grade', sa.String(length=50), nullable=True),
    sa.Column('photo_filename_proposal', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, server_default='pending'),
    sa.Column('admin_reviewer_id', sa.Integer(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.current_timestamp()),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_reviewer_id'], ['user.id'], name=op.f('fk_block_proposal_admin_reviewer_id_user')),
    sa.ForeignKeyConstraint(['proposer_id'], ['user.id'], name=op.f('fk_block_proposal_proposer_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_block_proposal'))
    )
    # For server_default on status and created_at, ensure your model also has `default` values
    # for the application layer. The server_default is for DB level.
    # My model has default='pending' for status and default=datetime.utcnow for created_at.
    # For 'created_at' specifically, sa.func.current_timestamp() is often for `server_default`.
    # If `default=datetime.utcnow` is used in model, that's client-side default.
    # The migration uses server_default for created_at which is fine.
    # For status, `server_default='pending'` is good.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('block_proposal')
    # ### end Alembic commands ###
